version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "hebertcisco"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
      labels:
        - "dependencies"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "hebertcisco"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
      labels:
        - "dependencies"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
