version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "dependabot"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "dependabot"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
